# Generated by Django 4.2.1 on 2023-05-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_type_animation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('link', models.CharField(default='', max_length=100)),
                ('img', models.CharField(default='', max_length=100)),
                ('animation_time', models.FloatField(default=0.0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotlight-brand+', to='products.brand')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotlight-type+', to='products.type')),
            ],
            options={
                'ordering': ['animation_time'],
            },
        ),
    ]
