# Generated by Django 4.2.1 on 2023-05-18 06:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('logo', models.CharField(default='', max_length=50)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('desc', models.TextField(default='')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default='')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('img', models.CharField(default='', max_length=50)),
                ('animation_time', models.FloatField(default=0.0)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('desc', models.TextField(default='')),
                ('sku', models.CharField(default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=11)),
                ('car_model', models.IntegerField()),
                ('odo', models.IntegerField()),
                ('gear_box', models.CharField(choices=[('MT', 'Manual'), ('AT', 'Automatic')], default='', max_length=50)),
                ('condition', models.CharField(choices=[('new', 'New'), ('old', 'Old')], default='', max_length=20)),
                ('fuel', models.CharField(choices=[('gas', 'Gasoline'), ('diesel', 'Diesel')], default='', max_length=20)),
                ('imgs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Brand')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.country', verbose_name='country')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.type', verbose_name='Type')),
            ],
        ),
    ]
