# Generated by Django 4.2.1 on 2023-05-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='animation_time',
        ),
    ]
