# Generated by Django 4.2.1 on 2023-05-24 12:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_type_animation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='imgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='type',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
